version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: weekly
  go-modules:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: infrastructure
  - package-ecosystem: gomod
    directories:
      - /spx-backend
      - /tools/spxls
      - /tools/ai
    patterns:
      - "*"
    multi-ecosystem-group: go-modules
