// Package tutorial is the Tutorial Class Framework.
//
// A Playground Course is an XGo program written against this package: the
// Course code states the task, observes what the learner does, and decides
// when the goal is reached. The framework translates those calls into frontend
// capabilities and delivers host events back onto the Course program's own
// goroutines.
//
// Three layers:
//
//	Course code (main_course.gox, interpreted by ixgo)
//	  ↓ method calls
//	this package (native Go, compiled into xgoexec.wasm)
//	  ↓ capabilities (blocking, over xgoexec's JSON bridge)
//	frontend host (the TutorialFrameworkHost the Tutorial module assembles)
//
// The contracts live in docs/develop/tutorial-v2:
// module_TutorialFramework.ts is the host-side interface and
// tutorial-class-framework.go the author-side API; both must stay in step
// with this package.
package tutorial

import "fmt"

// XGoPackage marks this as an XGo package (GopPackage is the legacy spelling).
// The classfile machinery relies on it to recognize a package usable as a
// project class framework.
const XGoPackage = true

// Course is the class every Course program derives from.
//
// XGo's classfile generates code like this, embedding this type in the
// Course's own class:
//
//	type Course struct { tutorial.Course }
//	func (this *Course) MainEntry() { ...Course code... }
//	func (this *Course) Main() { tutorial.XGot_Course_Main(this) }
//
// The namespace fields must be exported: XGo only upper-cases method calls
// (showMessage becomes ShowMessage), never field access. That is why Course
// code reads Editor.CodeEditor.filterAPIs, where the first two segments are
// capitalized fields and the last one a lower-cased method.
//
// The run state lives in the courseProgram field, and each namespace gets a
// pointer to it in initCourse. spx is structured the same way: its Game holds
// the scriptEventRegistry, which Game and the sprites share through
// scriptEventBindings.
type Course struct {
	Editor    Editor
	Copilot   Copilot
	Spotlight Spotlight

	courseProgram courseProgram
}

// CourseProto is the interface the Course class generated by XGo satisfies.
//
// The three methods come from different places:
//   - initCourse and Start come from this package's Course and are promoted
//     onto the generated class through embedding;
//   - MainEntry is generated by XGo, its body being the code the author wrote
//     at the top level of main_course.gox.
//
// initCourse is unexported, so only a type embedding tutorial.Course can
// possibly satisfy this interface. That is the same trick spx plays with
// Gamer.initGame, and it lets the entry function pull the embedded *Course out
// of an otherwise unknown user type to wire everything up.
type CourseProto interface {
	initCourse() *Course
	MainEntry()
	Start()
}

// contentRequest is the request shape of a capability that carries one piece
// of text. The field name content follows the wire convention already
// established by the #3424 skeleton, which is how the host decodes it.
type contentRequest struct {
	Content string `json:"content"`
}

// initCourse initializes the run state, points every namespace at that same
// state, and returns the embedded Course.
func (p *Course) initCourse() *Course {
	p.courseProgram.init()
	p.Editor.init(&p.courseProgram)
	p.Copilot.courseProgram = &p.courseProgram
	p.Spotlight.courseProgram = &p.courseProgram
	return p
}

// OnStart registers a course-start callback.
//
// It is called after MainEntry finishes, which is after every callback has
// been registered, so Course code can start judging right away inside onStart
// without worrying that the event callbacks are not attached yet.
//
// Course start is an event that fires once and takes the same path as the
// other onXxx: several callbacks may be registered, they start in
// registration order, each running to its first wait before the next starts,
// and then proceed independently (see startRuns). A start callback registered
// after the Course has started is never called.
func (p *Course) OnStart(handler func()) {
	register(&p.courseProgram, nil, func(struct{}) { handler() },
		func(h *handlers, r *registration[struct{}]) { h.courseStart = append(h.courseStart, r) })
}

// NewRunGroup creates a run group; see RunPolicy and RunGroup. Course code
// spells it newRunGroup.
func (p *Course) NewRunGroup(policy RunPolicy) RunGroup {
	return &runGroup{p: &p.courseProgram, policy: policy}
}

// groupOf recovers the internal type from a RunGroup given at registration;
// only this package implements that interface.
func groupOf(group RunGroup) *runGroup {
	g, ok := group.(*runGroup)
	if !ok {
		panic(fmt.Sprintf("tutorial: %T is not a RunGroup created by newRunGroup", group))
	}
	return g
}

// ShowPrelude displays the opening task guide and returns once the learner
// dismisses it. It differs from ShowMessage only in how the host presents it
// (opening guide versus ordinary dialog); on this side they are simply two
// capability names.
func (p *Course) ShowPrelude(preludeMessage string) {
	p.courseProgram.mustCallCapability("course_showPrelude", contentRequest{Content: preludeMessage}, nil)
}

// ShowMessage displays a dialog and returns once the learner dismisses it.
//
// Blocking is deliberate: the contract has presentation always wait for the
// learner to finish reading, never advancing on its own. That keeps Course
// code reading as a sequential script, so the author needs no notion of
// asynchrony.
func (p *Course) ShowMessage(message string) {
	p.courseProgram.mustCallCapability("course_showMessage", contentRequest{Content: message}, nil)
}

// ShowVideo plays a Course-local explanatory video and returns once the
// learner finishes watching or closes it.
//
// videoName is a declared video resource name, not a file path: videos are
// declared as assets/videos/<name>/index.json and the author writes
// showVideo "step-to". That lets the Course language service check while the
// Course is being written that the video exists and its name is not
// misspelled, rather than failing once the Course runs.
func (p *Course) ShowVideo(videoName string) {
	p.courseProgram.mustCallCapability("course_showVideo", struct {
		VideoName string `json:"videoName"`
	}{VideoName: videoName}, nil)
}

// Complete marks the Course completed.
//
// Completion semantics: no further triggers start runs and pending ones are
// abandoned, while callbacks already running or suspended execute their
// remaining statements (the host no-ops presentation capabilities by then).
// Once they all finish, the program ends and the executor reports the run as
// completed. Terminating right here instead is deliberately avoided: Complete
// is called from inside the author's callback, and forcing an exit would make
// "do the statements after complete run?" an unanswerable question.
//
// Repeated calls are ignored, see courseProgram.markCompleted.
func (p *Course) Complete() {
	if !p.courseProgram.markCompleted() {
		return
	}
	p.courseProgram.mustCallCapability("course_complete", struct{}{}, nil)
}

// CompleteWith is Complete carrying a line of feedback; the semantics are
// identical. The typical use is generating that line from the learner's final
// code with Copilot.generateText and passing it in here.
//
// The parameter is named message to match the contract
// (tutorial-class-framework.go), and the payload keeps the {content} shape
// shared by the presentation capabilities; a host reading some other field
// name should align with the contract.
func (p *Course) CompleteWith(message string) {
	if !p.courseProgram.markCompleted() {
		return
	}
	p.courseProgram.mustCallCapability("course_completeWith", contentRequest{Content: message}, nil)
}

// Start runs the Course program: start the runs of course start, start the
// dispatcher goroutine, then wait for the Course to end.
//
// Course start takes the same path as host events: this is the single trigger
// that starts every onStart. Author callbacks therefore have exactly two
// execution paths, runFrame on a run goroutine and the one MainEntry frame on
// the main goroutine.
//
// Three constraints make up the execution model (see the comments on
// courseProgram, runGroup and startRuns for the details):
//   - One at a time, several in flight: only the holder of the execution
//     token runs Course code at any instant, so shared variables never race;
//     a run releases the token while it waits on a waiting capability
//     (presentation, LLM) and the other runs proceed, so runs of one callback
//     may overlap, constrained by their run group's policy.
//   - Starts are ordered: triggers are handled in arrival order, and within
//     one trigger the callbacks start in registration order, each running to
//     its first wait or its end before the next starts. That is what backs
//     the contract's promise for editor.runtime.log, one run started per
//     entry, started in append order.
//   - Completion winds down: after complete, no new trigger starts a run;
//     runs already executing or suspended finish their remaining statements
//     (the host no-ops presentation capabilities by then) while queued runs
//     simply exit, and the program ends once they all do.
func (p *Course) Start() {
	program := &p.courseProgram
	// The main goroutine starts the course-start runs itself, and only then
	// starts the dispatcher for host events: the Course logically begins
	// before it observes the world. If the Course already completed inside
	// MainEntry, admitRun refuses to start them and no start callback runs.
	startRuns(program, program.handlerSnapshot().courseStart, struct{}{})
	events.goLive(program)
	program.awaitShutdown()
}

// XGot_Course_Main is the program entry the classfile convention expects,
// called by the Main that XGo generates.
//
// The XGot_ prefix (Gopt_ in the legacy spelling) marks a template receiver
// method: seeing it while importing this package, gogen registers the function
// as a method on the Course type, which is how the generated Main can reach
// it. spx's counterpart is XGot_Game_Main.
//
// The order matters: first take the embedded instance, initialize the state
// and take over the event entry (deliveries arriving before the program is
// ready are buffered from here on), then execute MainEntry, where the author's
// code registers its callbacks, and only then enter Start. The other way
// around, initCourse's reset would wipe the callbacks MainEntry registered.
// MainEntry executes as a run as well, so calling showMessage and friends
// straight from the top level works too.
func XGot_Course_Main(course CourseProto) {
	program := &course.initCourse().courseProgram
	events.attach(program)
	program.runFrame(newRun(), course.MainEntry)
	course.Start()
}
