name: Build and Deploy Backend

on:
  push:
    branches:
      - dev
      - ci-cd
    paths:
      - spx-backend/**
      - '!**/*.md'

env:
  DOCKER_HUB_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/builder-spx-backend:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v4

      - name: Build and push Docker image
        working-directory: spx-backend
        run: |
          docker build -t $DOCKER_HUB_IMAGE .
          docker push $DOCKER_HUB_IMAGE
