name: CI
on:
  push:
    branches:
      - '**'
    paths:
      - 'spx-gui/**'
      - '!**/*.md'
  pull_request:
    branches:
      - '**'
    paths:
      - 'spx-gui/**'
      - '!**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: spx-gui/package-lock.json

      - name: Install modules
        working-directory: spx-gui
        run: npm install

      - name: Run Vue TSC
        working-directory: spx-gui
        run: npm run type-check

      - name: Run ESLint
        working-directory: spx-gui
        run: npm run lint
