name: Validate (lint, test & ...)

on:
  push:
  pull_request:

jobs:
  spx-gui-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spx-gui
    steps:
      - uses: actions/checkout@v7

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.11.1
          cache: pnpm
          cache-dependency-path: spx-gui/pnpm-lock.yaml

      - name: Install Node modules
        run: pnpm install --frozen-lockfile

      - name: Run Vue TSC
        run: pnpm run type-check

      - name: Run ESLint
        run: pnpm run lint

      - name: Run format check
        run: pnpm run format-check

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.25.x
          cache: true
          cache-dependency-path: |
            tools/spxls/go.sum
            tools/ispx/go.sum
            tools/ai/go.sum

      - name: Build WASM
        run: ./build-wasm.sh

      - name: Run Vitest
        run: pnpm run test

      - name: Build
        run: pnpm run build

  tools-ai-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/ai
    steps:
      - uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.25.x
          cache: true
          cache-dependency-path: tools/ai/go.sum

      - name: Run unit test cases
        run: go test -v -race ./...
