[package]
name = "resvg-wasm"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"

[lib]
crate-type = ["cdylib"]

[dependencies]
resvg = { version = "0.47", default-features = false, features = ["text", "raster-images"] }
svgtypes = "0.16"
ttf-parser = "0.25"
wasm-bindgen = "=0.2.126"
js-sys = "0.3"
